name: conoce_gama
description: "Conoce Maracaibo."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:  
  uses-material-design: true
  fonts:
    - family: alcaldia_fonts
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic

  assets:
    - assets/images/brand/
    - assets/images/main/ 
    - assets/images/vector/
    - assets/images/axis/
    - assets/images/events_png/
    - assets/json/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
